-- ==============================================================================
-- CROWD CITY — COMPLETE TAMIL NADU ADMINISTRATIVE LOCATION HIERARCHY
-- Migration Version: v8_tamilnadu_location_hierarchy.sql
-- Relational Schema for 38 Districts -> Taluks -> Locations -> Local Bodies
-- ==============================================================================

-- 1. Districts Table
CREATE TABLE IF NOT EXISTS public.districts (
  id VARCHAR(50) PRIMARY KEY,
  code VARCHAR(10) UNIQUE NOT NULL,
  name VARCHAR(100) NOT NULL,
  tamil_name VARCHAR(100) NOT NULL,
  lat NUMERIC(10, 7),
  lng NUMERIC(10, 7),
  headquarters VARCHAR(100),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Taluks Table
CREATE TABLE IF NOT EXISTS public.taluks (
  id VARCHAR(100) PRIMARY KEY,
  district_id VARCHAR(50) NOT NULL REFERENCES public.districts(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  tamil_name VARCHAR(100),
  type VARCHAR(30) NOT NULL DEFAULT 'taluk',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Local Bodies Table
CREATE TABLE IF NOT EXISTS public.local_bodies (
  id VARCHAR(150) PRIMARY KEY,
  district_id VARCHAR(50) NOT NULL REFERENCES public.districts(id) ON DELETE CASCADE,
  taluk_id VARCHAR(100) REFERENCES public.taluks(id) ON DELETE SET NULL,
  name VARCHAR(150) NOT NULL,
  tamil_name VARCHAR(150),
  body_type VARCHAR(50) NOT NULL,
  tier VARCHAR(20) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Locations (Revenue Villages, Panchayats, Towns, Municipalities) Table
CREATE TABLE IF NOT EXISTS public.locations (
  id VARCHAR(150) PRIMARY KEY,
  district_id VARCHAR(50) NOT NULL REFERENCES public.districts(id) ON DELETE CASCADE,
  taluk_id VARCHAR(100) NOT NULL REFERENCES public.taluks(id) ON DELETE CASCADE,
  name VARCHAR(150) NOT NULL,
  tamil_name VARCHAR(150),
  location_type VARCHAR(50) NOT NULL,
  local_body_id VARCHAR(150) REFERENCES public.local_bodies(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_taluks_district ON public.taluks(district_id);
CREATE INDEX IF NOT EXISTS idx_locations_taluk ON public.locations(taluk_id);
CREATE INDEX IF NOT EXISTS idx_locations_district ON public.locations(district_id);
CREATE INDEX IF NOT EXISTS idx_locations_name ON public.locations(name);
CREATE INDEX IF NOT EXISTS idx_locations_type ON public.locations(location_type);
CREATE INDEX IF NOT EXISTS idx_local_bodies_taluk ON public.local_bodies(taluk_id);
CREATE INDEX IF NOT EXISTS idx_local_bodies_district ON public.local_bodies(district_id);
CREATE INDEX IF NOT EXISTS idx_local_bodies_type ON public.local_bodies(body_type);

-- Row Level Security
ALTER TABLE public.districts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.taluks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.local_bodies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read districts" ON public.districts FOR SELECT USING (true);
CREATE POLICY "Public read taluks" ON public.taluks FOR SELECT USING (true);
CREATE POLICY "Public read locations" ON public.locations FOR SELECT USING (true);
CREATE POLICY "Public read local_bodies" ON public.local_bodies FOR SELECT USING (true);

-- Seed Districts
INSERT INTO public.districts (id, code, name, tamil_name, lat, lng, headquarters) VALUES
('ariyalur', 'ari', 'Ariyalur', 'அரியலூர்', 11.1401, 79.0786, 'Ariyalur'),
('chengalpattu', 'cpt', 'Chengalpattu', 'செங்கல்பட்டு', 12.6841, 79.9836, 'Chengalpattu'),
('chennai', 'chn', 'Chennai', 'சென்னை', 13.0827, 80.2707, 'Chennai'),
('coimbatore', 'cbe', 'Coimbatore', 'கோயம்புத்தூர்', 11.0168, 76.9558, 'Coimbatore'),
('cuddalore', 'cud', 'Cuddalore', 'கடலூர்', 11.748, 79.7714, 'Cuddalore'),
('dharmapuri', 'dpi', 'Dharmapuri', 'தர்மபுரி', 12.1211, 78.1582, 'Dharmapuri'),
('dindigul', 'dgl', 'Dindigul', 'திண்டுக்கல்', 10.3673, 77.9803, 'Dindigul'),
('erode', 'erd', 'Erode', 'ஈரோடு', 11.341, 77.7172, 'Erode'),
('kallakurichi', 'kki', 'Kallakurichi', 'கள்ளக்குறிச்சி', 11.7384, 78.9597, 'Kallakurichi'),
('kancheepuram', 'kpm', 'Kancheepuram', 'காஞ்சிபுரம்', 12.8342, 79.7036, 'Kancheepuram'),
('kanniyakumari', 'kkm', 'Kanniyakumari', 'கன்னியாகுமரி', 8.0883, 77.5385, 'Kanniyakumari'),
('karur', 'krr', 'Karur', 'கரூர்', 10.9601, 78.0766, 'Karur'),
('krishnagiri', 'kgi', 'Krishnagiri', 'கிருஷ்ணகிரி', 12.5186, 78.2137, 'Krishnagiri'),
('madurai', 'mdu', 'Madurai', 'மதுரை', 9.9252, 78.1198, 'Madurai'),
('mayiladuthurai', 'myd', 'Mayiladuthurai', 'மயிலாடுதுறை', 11.1035, 79.6548, 'Mayiladuthurai'),
('nagapattinam', 'ngp', 'Nagapattinam', 'நாகப்பட்டினம்', 10.7672, 79.8449, 'Nagapattinam'),
('namakkal', 'nmk', 'Namakkal', 'நாமக்கல்', 11.2189, 78.1674, 'Namakkal'),
('nilgiris', 'nil', 'The Nilgiris', 'நீலகிரி', 11.4916, 76.7337, 'The Nilgiris'),
('perambalur', 'pbl', 'Perambalur', 'பெரம்பலூர்', 11.2342, 78.8821, 'Perambalur'),
('pudukkottai', 'pdk', 'Pudukkottai', 'புதுக்கோட்டை', 10.3797, 78.8208, 'Pudukkottai'),
('ramanathapuram', 'ram', 'Ramanathapuram', 'இராமநாதபுரம்', 9.3639, 78.8395, 'Ramanathapuram'),
('ranipet', 'rpt', 'Ranipet', 'ராணிப்பேட்டை', 12.9229, 79.3329, 'Ranipet'),
('salem', 'slm', 'Salem', 'சேலம்', 11.6643, 78.146, 'Salem'),
('sivaganga', 'svg', 'Sivaganga', 'சிவகங்கை', 9.8433, 78.4809, 'Sivaganga'),
('tenkasi', 'tks', 'Tenkasi', 'தென்காசி', 8.9594, 77.3161, 'Tenkasi'),
('thanjavur', 'tjr', 'Thanjavur', 'தஞ்சாவூர்', 10.787, 79.1378, 'Thanjavur'),
('theni', 'tni', 'Theni', 'தேனி', 10.0104, 77.4768, 'Theni'),
('thoothukudi', 'tcy', 'Thoothukudi', 'தூத்துக்குடி', 8.7642, 78.1348, 'Thoothukudi'),
('tiruchirappalli', 'try', 'Tiruchirappalli', 'திருச்சிராப்பள்ளி', 10.7905, 78.7047, 'Tiruchirappalli'),
('tirunelveli', 'tnv', 'Tirunelveli', 'திருநெல்வேலி', 8.7139, 77.7567, 'Tirunelveli'),
('tirupathur', 'tpt', 'Tirupathur', 'திருப்பத்தூர்', 12.4926, 78.5638, 'Tirupathur'),
('tiruppur', 'tup', 'Tiruppur', 'திருப்பூர்', 11.1085, 77.3411, 'Tiruppur'),
('tiruvallur', 'tlr', 'Tiruvallur', 'திருவள்ளூர்', 13.1432, 79.9083, 'Tiruvallur'),
('tiruvannamalai', 'tvm', 'Tiruvannamalai', 'திருவண்ணாமலை', 12.2253, 79.0747, 'Tiruvannamalai'),
('tiruvarur', 'tvr', 'Tiruvarur', 'திருவாரூர்', 10.7661, 79.6344, 'Tiruvarur'),
('vellore', 'vel', 'Vellore', 'வேலூர்', 12.9165, 79.1325, 'Vellore'),
('viluppuram', 'vpm', 'Viluppuram', 'விழுப்புரம்', 11.9401, 79.4861, 'Viluppuram'),
('virudhunagar', 'vnr', 'Virudhunagar', 'விருதுநகர்', 9.568, 77.9624, 'Virudhunagar')
ON CONFLICT (id) DO UPDATE SET 
  name = EXCLUDED.name, 
  tamil_name = EXCLUDED.tamil_name, 
  code = EXCLUDED.code;

-- Seed Taluks
INSERT INTO public.taluks (id, district_id, name, tamil_name, type) VALUES
('ari_ariyalur', 'ariyalur', 'Ariyalur', 'அரியலூர்', 'taluk'),
('ari_udayarpalayam', 'ariyalur', 'Udayarpalayam', 'உடையார்பாளையம்', 'taluk'),
('ari_sendurai', 'ariyalur', 'Sendurai', 'செந்துறை', 'taluk'),
('ari_andimadam', 'ariyalur', 'Andimadam', 'ஆண்டிமடம்', 'taluk'),
('cpt_chengalpattu', 'chengalpattu', 'Chengalpattu', 'செங்கல்பட்டு', 'taluk'),
('cpt_tambaram', 'chengalpattu', 'Tambaram', 'தாம்பரம்', 'taluk'),
('cpt_pallavaram', 'chengalpattu', 'Pallavaram', 'பல்லாவரம்', 'taluk'),
('cpt_maduranthakam', 'chengalpattu', 'Maduranthakam', 'மதுராந்தகம்', 'taluk'),
('cpt_cheyyur', 'chengalpattu', 'Cheyyur', 'செய்யூர்', 'taluk'),
('cpt_tiruporur', 'chengalpattu', 'Tiruporur', 'திருப்போரூர்', 'taluk'),
('cpt_vandalur', 'chengalpattu', 'Vandalur', 'வண்டலூர்', 'taluk'),
('cpt_kundrathur', 'chengalpattu', 'Kundrathur', 'குன்றத்தூர்', 'taluk'),
('chn_zone5', 'chennai', 'Zone 5 Royapuram', 'மண்டலம் 5 ராயபுரம்', 'revenue_division'),
('chn_zone8', 'chennai', 'Zone 8 Anna Nagar', 'மண்டலம் 8 அண்ணா நகர்', 'revenue_division'),
('chn_zone9', 'chennai', 'Zone 9 Teynampet', 'மண்டலம் 9 தேனாம்பேட்டை', 'revenue_division'),
('chn_zone10', 'chennai', 'Zone 10 Kodambakkam', 'மண்டலம் 10 கோடம்பாக்கம்', 'revenue_division'),
('chn_zone13', 'chennai', 'Zone 13 Adyar', 'மண்டலம் 13 அடையாறு', 'revenue_division'),
('chn_egmore', 'chennai', 'Egmore', 'எழும்பூர்', 'taluk'),
('chn_guindy', 'chennai', 'Guindy', 'கிண்டி', 'taluk'),
('chn_mylapore', 'chennai', 'Mylapore', 'மயிலாப்பூர்', 'taluk'),
('chn_mambalam', 'chennai', 'Mambalam', 'மாம்பலம்', 'taluk'),
('chn_tondiarpet', 'chennai', 'Tondiarpet', 'தண்டையார்பேட்டை', 'taluk'),
('chn_velachery', 'chennai', 'Velachery', 'வேளச்சேரி', 'taluk'),
('chn_perambur', 'chennai', 'Perambur', 'பெரம்பூர்', 'taluk'),
('chn_alandur', 'chennai', 'Alandur', 'ஆலந்தூர்', 'taluk'),
('chn_sholinganallur', 'chennai', 'Sholinganallur', 'சோழிங்கநல்லூர்', 'taluk'),
('cbe_sulur', 'coimbatore', 'Sulur', 'சூலூர்', 'taluk'),
('cbe_sulur_block', 'coimbatore', 'Sulur Block', 'சூலூர் ஒன்றியம்', 'block'),
('cbe_north', 'coimbatore', 'Coimbatore North', 'கோயம்புத்தூர் வடக்கு', 'taluk'),
('cbe_south', 'coimbatore', 'Coimbatore South', 'கோயம்புத்தூர் தெற்கு', 'taluk'),
('cbe_pollachi', 'coimbatore', 'Pollachi', 'பொள்ளாச்சி', 'taluk'),
('cbe_mettupalayam', 'coimbatore', 'Mettupalayam', 'மேட்டுப்பாளையம்', 'taluk'),
('cbe_annur', 'coimbatore', 'Annur', 'அன்னூர்', 'taluk'),
('cbe_madukkarai', 'coimbatore', 'Madukkarai', 'மதுக்கரை', 'taluk'),
('cbe_kinathukadavu', 'coimbatore', 'Kinathukadavu', 'கிணத்துக்கடவு', 'taluk'),
('cbe_valparai', 'coimbatore', 'Valparai', 'வால்பாறை', 'taluk'),
('cbe_perur', 'coimbatore', 'Perur', 'பேரூர்', 'taluk'),
('cbe_anaimalai', 'coimbatore', 'Anaimalai', 'ஆனைமலை', 'taluk'),
('cud_cuddalore', 'cuddalore', 'Cuddalore', 'கடலூர்', 'taluk'),
('cud_chidambaram', 'cuddalore', 'Chidambaram', 'சிதம்பரம்', 'taluk'),
('cud_panruti', 'cuddalore', 'Panruti', 'பண்ருட்டி', 'taluk'),
('cud_vriddhachalam', 'cuddalore', 'Vriddhachalam', 'விருத்தாசலம்', 'taluk'),
('cud_kurinjipadi', 'cuddalore', 'Kurinjipadi', 'குறிஞ்சிப்பாடி', 'taluk'),
('cud_tittakudi', 'cuddalore', 'Tittakudi', 'திட்டக்குடி', 'taluk'),
('cud_bhuvanagiri', 'cuddalore', 'Bhuvanagiri', 'புவனகிரி', 'taluk'),
('cud_srimushnam', 'cuddalore', 'Srimushnam', 'ஸ்ரீமுஷ்ணம்', 'taluk'),
('dpi_dharmapuri', 'dharmapuri', 'Dharmapuri', 'தர்மபுரி', 'taluk'),
('dpi_harur', 'dharmapuri', 'Harur', 'அரூர்', 'taluk'),
('dpi_palacode', 'dharmapuri', 'Palacode', 'பாலக்கோடு', 'taluk'),
('dpi_pennagaram', 'dharmapuri', 'Pennagaram', 'பென்னாகரம்', 'taluk'),
('dpi_pappireddipatti', 'dharmapuri', 'Pappireddipatti', 'பாப்பிரெட்டிப்பட்டி', 'taluk'),
('dpi_karimangalam', 'dharmapuri', 'Karimangalam', 'காரிமங்கலம்', 'taluk'),
('dpi_nallampalli', 'dharmapuri', 'Nallampalli', 'நல்லம்பள்ளி', 'taluk'),
('dgl_dindigul_east', 'dindigul', 'Dindigul East', 'திண்டுக்கல் கிழக்கு', 'taluk'),
('dgl_dindigul_west', 'dindigul', 'Dindigul West', 'திண்டுக்கல் மேற்கு', 'taluk'),
('dgl_palani', 'dindigul', 'Palani', 'பழனி', 'taluk'),
('dgl_kodaikanal', 'dindigul', 'Kodaikanal', 'கொடைக்கானல்', 'taluk'),
('dgl_natham', 'dindigul', 'Natham', 'நத்தம்', 'taluk'),
('dgl_nilakkottai', 'dindigul', 'Nilakkottai', 'நிலக்கோட்டை', 'taluk'),
('dgl_attur', 'dindigul', 'Attur', 'ஆத்தூர்', 'taluk'),
('dgl_vedasandur', 'dindigul', 'Vedasandur', 'வேடசந்தூர்', 'taluk'),
('dgl_gujjiliamparai', 'dindigul', 'Gujjiliamparai', 'குஜிலியம்பாறை', 'taluk'),
('erd_erode', 'erode', 'Erode', 'ஈரோடு', 'taluk'),
('erd_bhavani', 'erode', 'Bhavani', 'பவானி', 'taluk'),
('erd_gobichettipalayam', 'erode', 'Gobichettipalayam', 'கோபிசெட்டிபாளையம்', 'taluk'),
('erd_perundurai', 'erode', 'Perundurai', 'பெருந்துறை', 'taluk'),
('erd_anthiyur', 'erode', 'Anthiyur', 'அந்தியூர்', 'taluk'),
('erd_sathyamangalam', 'erode', 'Sathyamangalam', 'சத்தியமங்கலம்', 'taluk'),
('erd_kodumudi', 'erode', 'Kodumudi', 'கொடுமுடி', 'taluk'),
('erd_modakkurichi', 'erode', 'Modakkurichi', 'மொடக்குறிச்சி', 'taluk'),
('erd_thalavadi', 'erode', 'Thalavadi', 'தாளவாடி', 'taluk'),
('kki_kallakurichi', 'kallakurichi', 'Kallakurichi', 'கள்ளக்குறிச்சி', 'taluk'),
('kki_sankarapuram', 'kallakurichi', 'Sankarapuram', 'சங்கராபுரம்', 'taluk'),
('kki_chinnasalem', 'kallakurichi', 'Chinnasalem', 'சின்னசேலம்', 'taluk'),
('kki_ulundurpet', 'kallakurichi', 'Ulundurpet', 'உளுந்தூர்பேட்டை', 'taluk'),
('kki_tirukoilur', 'kallakurichi', 'Tirukoilur', 'திருக்கோவிலூர்', 'taluk'),
('kki_kalvarayan_hills', 'kallakurichi', 'Kalvarayan Hills', 'கல்வராயன் மலை', 'taluk'),
('kpm_kancheepuram', 'kancheepuram', 'Kancheepuram', 'காஞ்சிபுரம்', 'taluk'),
('kpm_sriperumbudur', 'kancheepuram', 'Sriperumbudur', 'ஸ்ரீபெரும்புதூர்', 'taluk'),
('kpm_walajabad', 'kancheepuram', 'Walajabad', 'வாலாஜாபாத்', 'taluk'),
('kpm_kundrathur', 'kancheepuram', 'Kundrathur', 'குன்றத்தூர்', 'taluk'),
('kpm_uthiramerur', 'kancheepuram', 'Uthiramerur', 'உத்திரமேரூர்', 'taluk'),
('kkm_agastheeswaram', 'kanniyakumari', 'Agastheeswaram', 'அகத்தீஸ்வரம்', 'taluk'),
('kkm_thovalai', 'kanniyakumari', 'Thovalai', 'தோவாளை', 'taluk'),
('kkm_kalkulam', 'kanniyakumari', 'Kalkulam', 'கல்குளம்', 'taluk'),
('kkm_vilavancode', 'kanniyakumari', 'Vilavancode', 'விளவங்கோடு', 'taluk'),
('kkm_killiyoor', 'kanniyakumari', 'Killiyoor', 'கிள்ளியூர்', 'taluk'),
('kkm_thiruvattar', 'kanniyakumari', 'Thiruvattar', 'திருவட்டார்', 'taluk'),
('krr_karur', 'karur', 'Karur', 'கரூர்', 'taluk'),
('krr_kulithalai', 'karur', 'Kulithalai', 'குளித்தலை', 'taluk'),
('krr_aravakurichi', 'karur', 'Aravakurichi', 'அரவக்குறிச்சி', 'taluk'),
('krr_krishnarayapuram', 'karur', 'Krishnarayapuram', 'கிருஷ்ணராயபுரம்', 'taluk'),
('krr_manmangalam', 'karur', 'Manmangalam', 'மண்மங்கலம்', 'taluk'),
('krr_pugalur', 'karur', 'Pugalur', 'புகழூர்', 'taluk'),
('krr_kadavur', 'karur', 'Kadavur', 'கடவூர்', 'taluk'),
('kgi_krishnagiri', 'krishnagiri', 'Krishnagiri', 'கிருஷ்ணகிரி', 'taluk'),
('kgi_hosur', 'krishnagiri', 'Hosur', 'ஓசூர்', 'taluk'),
('kgi_denkanikottai', 'krishnagiri', 'Denkanikottai', 'தேன்கனிக்கோட்டை', 'taluk'),
('kgi_pochampalli', 'krishnagiri', 'Pochampalli', 'போச்சம்பள்ளி', 'taluk'),
('kgi_uthangarai', 'krishnagiri', 'Uthangarai', 'ஊத்தங்கரை', 'taluk'),
('kgi_bargur', 'krishnagiri', 'Bargur', 'பர்கூர்', 'taluk'),
('kgi_shoolagiri', 'krishnagiri', 'Shoolagiri', 'சூளகிரி', 'taluk'),
('kgi_kelamangalam', 'krishnagiri', 'Kelamangalam', 'கேளமங்கலம்', 'taluk'),
('mdu_north', 'madurai', 'Madurai North', 'மதுரை வடக்கு', 'taluk'),
('mdu_south', 'madurai', 'Madurai South', 'மதுரை தெற்கு', 'taluk'),
('mdu_melur', 'madurai', 'Melur', 'மேலூர்', 'taluk'),
('mdu_thirumangalam', 'madurai', 'Thirumangalam', 'திருமங்கலம்', 'taluk'),
('mdu_usilampatti', 'madurai', 'Usilampatti', 'உசிலம்பட்டி', 'taluk'),
('mdu_vadipatti', 'madurai', 'Vadipatti', 'வாடிப்பட்டி', 'taluk'),
('mdu_peraiyur', 'madurai', 'Peraiyur', 'பேரையூர்', 'taluk'),
('mdu_thiruparankundram', 'madurai', 'Thiruparankundram', 'திருப்பரங்குன்றம்', 'taluk'),
('myd_mayiladuthurai', 'mayiladuthurai', 'Mayiladuthurai', 'மயிலாடுதுறை', 'taluk'),
('myd_sirkazhi', 'mayiladuthurai', 'Sirkazhi', 'சீர்காழி', 'taluk'),
('myd_tharangambadi', 'mayiladuthurai', 'Tharangambadi', 'தரங்கம்பாடி', 'taluk'),
('myd_kuthalam', 'mayiladuthurai', 'Kuthalam', 'குத்தாலம்', 'taluk'),
('ngp_nagapattinam', 'nagapattinam', 'Nagapattinam', 'நாகப்பட்டினம்', 'taluk'),
('ngp_vedaranyam', 'nagapattinam', 'Vedaranyam', 'வேதாரண்யம்', 'taluk'),
('ngp_kilvelur', 'nagapattinam', 'Kilvelur', 'கீழ்வேளூர்', 'taluk'),
('ngp_thirukkuvalai', 'nagapattinam', 'Thirukkuvalai', 'திருக்குவளை', 'taluk'),
('nmk_namakkal', 'namakkal', 'Namakkal', 'நாமக்கல்', 'taluk'),
('nmk_tiruchengode', 'namakkal', 'Tiruchengode', 'திருச்செங்கோடு', 'taluk'),
('nmk_rasipuram', 'namakkal', 'Rasipuram', 'ராசிபுரம்', 'taluk'),
('nmk_paramathi_velur', 'namakkal', 'Paramathi Velur', 'பரமத்தி வேலூர்', 'taluk'),
('nmk_kolli_hills', 'namakkal', 'Kolli Hills', 'கொல்லிமலை', 'taluk'),
('nmk_sendamangalam', 'namakkal', 'Sendamangalam', 'சேந்தமங்கலம்', 'taluk'),
('nmk_kumarapalayam', 'namakkal', 'Kumarapalayam', 'குமாரபாளையம்', 'taluk'),
('nmk_mohanur', 'namakkal', 'Mohanur', 'மோகனூர்', 'taluk'),
('nil_udhagamandalam', 'nilgiris', 'Udhagamandalam', 'உதகமண்டலம்', 'taluk'),
('nil_coonoor', 'nilgiris', 'Coonoor', 'குன்னூர்', 'taluk'),
('nil_kotagiri', 'nilgiris', 'Kotagiri', 'கோத்தகிரி', 'taluk'),
('nil_gudalur', 'nilgiris', 'Gudalur', 'கூடலூர்', 'taluk'),
('nil_pandalur', 'nilgiris', 'Pandalur', 'பந்தலூர்', 'taluk'),
('nil_kundah', 'nilgiris', 'Kundah', 'குந்தா', 'taluk'),
('pbl_perambalur', 'perambalur', 'Perambalur', 'பெரம்பலூர்', 'taluk'),
('pbl_veppanthattai', 'perambalur', 'Veppanthattai', 'வேப்பந்தட்டை', 'taluk'),
('pbl_kunnam', 'perambalur', 'Kunnam', 'குன்னம்', 'taluk'),
('pbl_alathur', 'perambalur', 'Alathur', 'ஆலத்தூர்', 'taluk'),
('pdk_pudukkottai', 'pudukkottai', 'Pudukkottai', 'புதுக்கோட்டை', 'taluk'),
('pdk_aranthangi', 'pudukkottai', 'Aranthangi', 'அறந்தாங்கி', 'taluk'),
('pdk_illuppur', 'pudukkottai', 'Illuppur', 'இலுப்பூர்', 'taluk'),
('pdk_karambakkudi', 'pudukkottai', 'Karambakkudi', 'கறம்பக்குடி', 'taluk'),
('pdk_kulathur', 'pudukkottai', 'Kulathur', 'குளத்தூர்', 'taluk'),
('pdk_alangudi', 'pudukkottai', 'Alangudi', 'ஆலங்குடி', 'taluk'),
('pdk_gandarvakottai', 'pudukkottai', 'Gandarvakottai', 'கந்தர்வக்கோட்டை', 'taluk'),
('pdk_avudaiyarkoil', 'pudukkottai', 'Avudaiyarkoil', 'ஆவுடையார்கோவில்', 'taluk'),
('pdk_manamelkudi', 'pudukkottai', 'Manamelkudi', 'மணமேல்குடி', 'taluk'),
('pdk_viralimalai', 'pudukkottai', 'Viralimalai', 'விராலிமலை', 'taluk'),
('ram_ramanathapuram', 'ramanathapuram', 'Ramanathapuram', 'இராமநாதபுரம்', 'taluk'),
('ram_rameswaram', 'ramanathapuram', 'Rameswaram', 'ராமேஸ்வரம்', 'taluk'),
('ram_paramakudi', 'ramanathapuram', 'Paramakudi', 'பரமக்குடி', 'taluk'),
('ram_tiruvadanai', 'ramanathapuram', 'Tiruvadanai', 'திருவாடானை', 'taluk'),
('ram_r_s_mangalam', 'ramanathapuram', 'RS Mangalam', 'ஆர்.எஸ்.மங்கலம்', 'taluk'),
('ram_mudukulathur', 'ramanathapuram', 'Mudukulathur', 'முதுகுளத்தூர்', 'taluk'),
('ram_kamuthi', 'ramanathapuram', 'Kamuthi', 'கமுதி', 'taluk'),
('ram_kilakarai', 'ramanathapuram', 'Kilakarai', 'கீழக்கரை', 'taluk'),
('ram_kadaladi', 'ramanathapuram', 'Kadaladi', 'கடலாடி', 'taluk'),
('rpt_ranipet', 'ranipet', 'Ranipet', 'ராணிப்பேட்டை', 'taluk'),
('rpt_walajah', 'ranipet', 'Walajah', 'வாலாஜா', 'taluk'),
('rpt_arcot', 'ranipet', 'Arcot', 'ஆற்காடு', 'taluk'),
('rpt_arakkonam', 'ranipet', 'Arakkonam', 'அரக்கோணம்', 'taluk'),
('rpt_sholinghur', 'ranipet', 'Sholinghur', 'சோளிங்கர்', 'taluk'),
('rpt_nemili', 'ranipet', 'Nemili', 'நெமிலி', 'taluk'),
('slm_salem', 'salem', 'Salem', 'சேலம்', 'taluk'),
('slm_attur', 'salem', 'Attur', 'ஆத்தூர்', 'taluk'),
('slm_mettur', 'salem', 'Mettur', 'மேட்டூர்', 'taluk'),
('slm_omalur', 'salem', 'Omalur', 'ஓமலூர்', 'taluk'),
('slm_edappadi', 'salem', 'Edappadi', 'எடப்பாடி', 'taluk'),
('slm_sankari', 'salem', 'Sankari', 'சங்ககிரி', 'taluk'),
('slm_valapady', 'salem', 'Valapady', 'வாழப்பாடி', 'taluk'),
('slm_gangavalli', 'salem', 'Gangavalli', 'கங்கவல்லி', 'taluk'),
('slm_yercaud', 'salem', 'Yercaud', 'ஏற்காடு', 'taluk'),
('slm_kadaiyampatti', 'salem', 'Kadaiyampatti', 'காடையாம்பட்டி', 'taluk'),
('svg_sivaganga', 'sivaganga', 'Sivaganga', 'சிவகங்கை', 'taluk'),
('svg_karaikudi', 'sivaganga', 'Karaikudi', 'காரைக்குடி', 'taluk'),
('svg_devakottai', 'sivaganga', 'Devakottai', 'தேவகோட்டை', 'taluk'),
('svg_manamadurai', 'sivaganga', 'Manamadurai', 'மானாமதுரை', 'taluk'),
('svg_tiruppattur', 'sivaganga', 'Tiruppattur', 'திருப்பத்தூர்', 'taluk'),
('svg_ilayangudi', 'sivaganga', 'Ilayangudi', 'இளையான்குடி', 'taluk'),
('svg_kalaiyarkovil', 'sivaganga', 'Kalaiyarkovil', 'காளையார்கோவில்', 'taluk'),
('svg_singampunari', 'sivaganga', 'Singampunari', 'சிங்கம்புணரி', 'taluk'),
('tks_tenkasi', 'tenkasi', 'Tenkasi', 'தென்காசி', 'taluk'),
('tks_sankarankovil', 'tenkasi', 'Sankarankovil', 'சங்கரன்கோவில்', 'taluk'),
('tks_kadayanallur', 'tenkasi', 'Kadayanallur', 'கடையநல்லூர்', 'taluk'),
('tks_shenkottai', 'tenkasi', 'Shenkottai', 'செங்கோட்டை', 'taluk'),
('tks_sivagiri', 'tenkasi', 'Sivagiri', 'சிவகிரி', 'taluk'),
('tks_veerakeralamputhur', 'tenkasi', 'Veerakeralamputhur', 'வீரகேரளம்புதூர்', 'taluk'),
('tks_alankulam', 'tenkasi', 'Alankulam', 'ஆலங்குளம்', 'taluk'),
('tks_thiruvengadam', 'tenkasi', 'Thiruvengadam', 'திருவேங்கடம்', 'taluk'),
('tjr_thanjavur', 'thanjavur', 'Thanjavur', 'தஞ்சாவூர்', 'taluk'),
('tjr_kumbakonam', 'thanjavur', 'Kumbakonam', 'கும்பகோணம்', 'taluk'),
('tjr_papanasam', 'thanjavur', 'Papanasam', 'பாபநாசம்', 'taluk'),
('tjr_pattukkottai', 'thanjavur', 'Pattukkottai', 'பட்டுக்கோட்டை', 'taluk'),
('tjr_orathanadu', 'thanjavur', 'Orathanadu', 'ஒரத்தநாடு', 'taluk'),
('tjr_thiruvaiyaru', 'thanjavur', 'Thiruvaiyaru', 'திருவையாறு', 'taluk'),
('tjr_peravurani', 'thanjavur', 'Peravurani', 'பேராவூரணி', 'taluk'),
('tjr_budalur', 'thanjavur', 'Budalur', 'பூதலூர்', 'taluk'),
('tjr_thiruvidaimarudur', 'thanjavur', 'Thiruvidaimarudur', 'திருவிடைமருதூர்', 'taluk'),
('tni_theni', 'theni', 'Theni', 'தேனி', 'taluk'),
('tni_periyakulam', 'theni', 'Periyakulam', 'பெரியகுளம்', 'taluk'),
('tni_bodinayakanur', 'theni', 'Bodinayakanur', 'போடிநாயக்கனூர்', 'taluk'),
('tni_uthamapalayam', 'theni', 'Uthamapalayam', 'உத்தமபாளையம்', 'taluk'),
('tni_andipatti', 'theni', 'Andipatti', 'ஆண்டிபட்டி', 'taluk'),
('tcy_thoothukudi', 'thoothukudi', 'Thoothukudi', 'தூத்துக்குடி', 'taluk'),
('tcy_kovilpatti', 'thoothukudi', 'Kovilpatti', 'கோவில்பட்டி', 'taluk'),
('tcy_tiruchendur', 'thoothukudi', 'Tiruchendur', 'திருச்செந்தூர்', 'taluk'),
('tcy_srivaikuntam', 'thoothukudi', 'Srivaikuntam', 'ஸ்ரீவைகுண்டம்', 'taluk'),
('tcy_vilathikulam', 'thoothukudi', 'Vilathikulam', 'விளாத்திகுளம்', 'taluk'),
('tcy_ottapidaram', 'thoothukudi', 'Ottapidaram', 'ஒட்டப்பிடாரம்', 'taluk'),
('tcy_sattankulam', 'thoothukudi', 'Sattankulam', 'சாத்தான்குளம்', 'taluk'),
('tcy_eral', 'thoothukudi', 'Eral', 'ஏரல்', 'taluk'),
('try_trichy_west', 'tiruchirappalli', 'Tiruchirappalli West', 'திருச்சிராப்பள்ளி மேற்கு', 'taluk'),
('try_trichy_east', 'tiruchirappalli', 'Tiruchirappalli East', 'திருச்சிராப்பள்ளி கிழக்கு', 'taluk'),
('try_srirangam', 'tiruchirappalli', 'Srirangam', 'ஸ்ரீரங்கம்', 'taluk'),
('try_thiruverumbur', 'tiruchirappalli', 'Thiruverumbur', 'திருவெறும்பூர்', 'taluk'),
('try_manapparai', 'tiruchirappalli', 'Manapparai', 'மணப்பாறை', 'taluk'),
('try_musiri', 'tiruchirappalli', 'Musiri', 'முசிறி', 'taluk'),
('try_lalgudi', 'tiruchirappalli', 'Lalgudi', 'லால்குடி', 'taluk'),
('try_thuraiyur', 'tiruchirappalli', 'Thuraiyur', 'துறையூர்', 'taluk'),
('try_marungapuri', 'tiruchirappalli', 'Marungapuri', 'மருங்காபுரி', 'taluk'),
('tnv_tirunelveli', 'tirunelveli', 'Tirunelveli', 'திருநெல்வேலி', 'taluk'),
('tnv_palayamkottai', 'tirunelveli', 'Palayamkottai', 'பாளையங்கோட்டை', 'taluk'),
('tnv_ambasamudram', 'tirunelveli', 'Ambasamudram', 'அம்பாசமுத்திரம்', 'taluk'),
('tnv_cheranmahadevi', 'tirunelveli', 'Cheranmahadevi', 'சேரன்மகாதேவி', 'taluk'),
('tnv_nanguneri', 'tirunelveli', 'Nanguneri', 'நாங்குநேரி', 'taluk'),
('tnv_radhapuram', 'tirunelveli', 'Radhapuram', 'ராதாபுரம்', 'taluk'),
('tnv_tisayanvilai', 'tirunelveli', 'Tisayanvilai', 'திசையன்விளை', 'taluk'),
('tpt_tirupathur', 'tirupathur', 'Tirupathur', 'திருப்பத்தூர்', 'taluk'),
('tpt_vaniyambadi', 'tirupathur', 'Vaniyambadi', 'வாணியம்பாடி', 'taluk'),
('tpt_ambur', 'tirupathur', 'Ambur', 'ஆம்பூர்', 'taluk'),
('tpt_natrampalli', 'tirupathur', 'Natrampalli', 'நாட்ராம்பள்ளி', 'taluk'),
('tup_tiruppur_north', 'tiruppur', 'Tiruppur North', 'திருப்பூர் வடக்கு', 'taluk'),
('tup_tiruppur_south', 'tiruppur', 'Tiruppur South', 'திருப்பூர் தெற்கு', 'taluk'),
('tup_avinashi', 'tiruppur', 'Avinashi', 'அவினாசி', 'taluk'),
('tup_palladam', 'tiruppur', 'Palladam', 'பல்லடம்', 'taluk'),
('tup_dharapuram', 'tiruppur', 'Dharapuram', 'தாராபுரம்', 'taluk'),
('tup_kangeyam', 'tiruppur', 'Kangeyam', 'காங்கேயம்', 'taluk'),
('tup_udumalaipettai', 'tiruppur', 'Udumalaipettai', 'உடுமலைப்பேட்டை', 'taluk'),
('tup_madathukulam', 'tiruppur', 'Madathukulam', 'மடத்துக்குளம்', 'taluk'),
('tup_uthukuli', 'tiruppur', 'Uthukuli', 'ஊத்துக்குளி', 'taluk'),
('tlr_tiruvallur', 'tiruvallur', 'Tiruvallur', 'திருவள்ளூர்', 'taluk'),
('tlr_avadi', 'tiruvallur', 'Avadi', 'ஆவடி', 'taluk'),
('tlr_poonamallee', 'tiruvallur', 'Poonamallee', 'பூந்தமல்லி', 'taluk'),
('tlr_ponneri', 'tiruvallur', 'Ponneri', 'பொன்னேரி', 'taluk'),
('tlr_gummidipoondi', 'tiruvallur', 'Gummidipoondi', 'கும்மிடிப்பூண்டி', 'taluk'),
('tlr_tiruttani', 'tiruvallur', 'Tiruttani', 'திருத்தணி', 'taluk'),
('tlr_uthukottai', 'tiruvallur', 'Uthukottai', 'ஊத்துக்கோட்டை', 'taluk'),
('tlr_pallipattu', 'tiruvallur', 'Pallipattu', 'பள்ளிப்பட்டு', 'taluk'),
('tvm_tiruvannamalai', 'tiruvannamalai', 'Tiruvannamalai', 'திருவண்ணாமலை', 'taluk'),
('tvm_arani', 'tiruvannamalai', 'Arani', 'ஆரணி', 'taluk'),
('tvm_cheyyar', 'tiruvannamalai', 'Cheyyar', 'செய்யாறு', 'taluk'),
('tvm_polur', 'tiruvannamalai', 'Polur', 'போளூர்', 'taluk'),
('tvm_vandavasi', 'tiruvannamalai', 'Vandavasi', 'வந்தவாசி', 'taluk'),
('tvm_chengam', 'tiruvannamalai', 'Chengam', 'செங்கம்', 'taluk'),
('tvm_thandarampattu', 'tiruvannamalai', 'Thandarampattu', 'தண்டராம்பட்டு', 'taluk'),
('tvm_kalasapakkam', 'tiruvannamalai', 'Kalasapakkam', 'கலசப்பாக்கம்', 'taluk'),
('tvm_jawadhu_hills', 'tiruvannamalai', 'Jawadhu Hills', 'ஜவ்வாது மலை', 'taluk'),
('tvr_tiruvarur', 'tiruvarur', 'Tiruvarur', 'திருவாரூர்', 'taluk'),
('tvr_mannargudi', 'tiruvarur', 'Mannargudi', 'மன்னார்குடி', 'taluk'),
('tvr_thiruthuraipoondi', 'tiruvarur', 'Thiruthuraipoondi', 'திருத்துறைப்பூண்டி', 'taluk'),
('tvr_nannilam', 'tiruvarur', 'Nannilam', 'நன்னிலம்', 'taluk'),
('tvr_kudavasal', 'tiruvarur', 'Kudavasal', 'குடவாசல்', 'taluk'),
('tvr_valangaiman', 'tiruvarur', 'Valangaiman', 'வலங்கைமான்', 'taluk'),
('tvr_needamangalam', 'tiruvarur', 'Needamangalam', 'நீடாமங்கலம்', 'taluk'),
('tvr_koothanallur', 'tiruvarur', 'Koothanallur', 'கூத்தநல்லூர்', 'taluk'),
('vel_vellore', 'vellore', 'Vellore', 'வேலூர்', 'taluk'),
('vel_katpadi', 'vellore', 'Katpadi', 'காட்பாடி', 'taluk'),
('vel_gudiyatham', 'vellore', 'Gudiyatham', 'குடியாத்தம்', 'taluk'),
('vel_anaicut', 'vellore', 'Anaicut', 'அணைக்கட்டு', 'taluk'),
('vel_kv_kuppam', 'vellore', 'KV Kuppam', 'கே.வி.குப்பம்', 'taluk'),
('vel_pernambut', 'vellore', 'Pernambut', 'பேரணாம்பட்டு', 'taluk'),
('vpm_viluppuram', 'viluppuram', 'Viluppuram', 'விழுப்புரம்', 'taluk'),
('vpm_tindivanam', 'viluppuram', 'Tindivanam', 'திண்டிவனம்', 'taluk'),
('vpm_gingee', 'viluppuram', 'Gingee', 'செஞ்சி', 'taluk'),
('vpm_vanur', 'viluppuram', 'Vanur', 'வானூர்', 'taluk'),
('vpm_vikravandi', 'viluppuram', 'Vikravandi', 'விக்ரவாண்டி', 'taluk'),
('vpm_kandachipuram', 'viluppuram', 'Kandachipuram', 'கண்டாச்சிபுரம்', 'taluk'),
('vpm_marakkanam', 'viluppuram', 'Marakkanam', 'மரக்காணம்', 'taluk'),
('vnr_virudhunagar', 'virudhunagar', 'Virudhunagar', 'விருதுநகர்', 'taluk'),
('vnr_sivakasi', 'virudhunagar', 'Sivakasi', 'சிவகாசி', 'taluk'),
('vnr_srivilliputhur', 'virudhunagar', 'Srivilliputhur', 'ஸ்ரீவில்லிபுத்தூர்', 'taluk'),
('vnr_rajapalayam', 'virudhunagar', 'Rajapalayam', 'ராஜபாளையம்', 'taluk'),
('vnr_aruppukkottai', 'virudhunagar', 'Aruppukkottai', 'அருப்புக்கோட்டை', 'taluk'),
('vnr_sattur', 'virudhunagar', 'Sattur', 'சாத்தூர்', 'taluk'),
('vnr_kariyapatti', 'virudhunagar', 'Kariyapatti', 'காரியாபட்டி', 'taluk'),
('vnr_tiruchuli', 'virudhunagar', 'Tiruchuli', 'திருச்சுழி', 'taluk'),
('vnr_vembakottai', 'virudhunagar', 'Vembakottai', 'வெம்பக்கோட்டை', 'taluk')
ON CONFLICT (id) DO UPDATE SET 
  name = EXCLUDED.name, 
  tamil_name = EXCLUDED.tamil_name, 
  district_id = EXCLUDED.district_id;
