-- ==============================================================================
-- CROWD CITY — COMPLETE TAMIL NADU ADMINISTRATIVE LOCATION HIERARCHY
-- Migration Version: v8_tamilnadu_location_hierarchy.sql (Step 1 Harmonized)
-- Relational Schema for 38 Districts -> 313 CRA Taluks -> Locations -> Local Bodies
-- ==============================================================================

-- 1. Districts Table
CREATE TABLE IF NOT EXISTS public.districts (
  id VARCHAR(50) PRIMARY KEY,
  code VARCHAR(10) UNIQUE NOT NULL,
  name VARCHAR(100) NOT NULL,
  tamil_name VARCHAR(100) NOT NULL,
  lat NUMERIC(10, 7),
  lng NUMERIC(10, 7),
  headquarters VARCHAR(100),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Taluks Table
CREATE TABLE IF NOT EXISTS public.taluks (
  id VARCHAR(100) PRIMARY KEY,
  district_id VARCHAR(50) NOT NULL REFERENCES public.districts(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  tamil_name VARCHAR(100),
  type VARCHAR(30) NOT NULL DEFAULT 'taluk',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Local Bodies Table
CREATE TABLE IF NOT EXISTS public.local_bodies (
  id VARCHAR(150) PRIMARY KEY,
  district_id VARCHAR(50) NOT NULL REFERENCES public.districts(id) ON DELETE CASCADE,
  taluk_id VARCHAR(100) REFERENCES public.taluks(id) ON DELETE SET NULL,
  name VARCHAR(150) NOT NULL,
  tamil_name VARCHAR(150),
  body_type VARCHAR(50) NOT NULL,
  tier VARCHAR(20) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Locations Table
CREATE TABLE IF NOT EXISTS public.locations (
  id VARCHAR(150) PRIMARY KEY,
  district_id VARCHAR(50) NOT NULL REFERENCES public.districts(id) ON DELETE CASCADE,
  taluk_id VARCHAR(100) NOT NULL REFERENCES public.taluks(id) ON DELETE CASCADE,
  name VARCHAR(150) NOT NULL,
  tamil_name VARCHAR(150),
  location_type VARCHAR(50) NOT NULL,
  local_body_id VARCHAR(150) REFERENCES public.local_bodies(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_taluks_district ON public.taluks(district_id);
CREATE INDEX IF NOT EXISTS idx_locations_taluk ON public.locations(taluk_id);
CREATE INDEX IF NOT EXISTS idx_locations_district ON public.locations(district_id);
CREATE INDEX IF NOT EXISTS idx_locations_name ON public.locations(name);
CREATE INDEX IF NOT EXISTS idx_locations_type ON public.locations(location_type);
CREATE INDEX IF NOT EXISTS idx_local_bodies_taluk ON public.local_bodies(taluk_id);
CREATE INDEX IF NOT EXISTS idx_local_bodies_district ON public.local_bodies(district_id);
CREATE INDEX IF NOT EXISTS idx_local_bodies_type ON public.local_bodies(body_type);

-- RLS
ALTER TABLE public.districts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.taluks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.local_bodies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read districts" ON public.districts FOR SELECT USING (true);
CREATE POLICY "Public read taluks" ON public.taluks FOR SELECT USING (true);
CREATE POLICY "Public read locations" ON public.locations FOR SELECT USING (true);
CREATE POLICY "Public read local_bodies" ON public.local_bodies FOR SELECT USING (true);

-- Step 1 Cleanup Obsolete Non-Taluk Entities
DELETE FROM public.taluks WHERE id IN ('chn_zone5', 'chn_zone8', 'chn_zone9', 'chn_zone10', 'chn_zone13', 'cbe_sulur_block', 'cpt_kundrathur');

-- Seed Official 313 CRA Taluks
INSERT INTO public.taluks (id, district_id, name, tamil_name, type) VALUES
('ari_andimadam', 'ariyalur', 'Andimadam', 'ஆண்டிமடம்', 'taluk'),
('ari_ariyalur', 'ariyalur', 'Ariyalur', 'அரியலூர்', 'taluk'),
('ari_sendurai', 'ariyalur', 'Sendurai', 'செந்துறை', 'taluk'),
('ari_udayarpalayam', 'ariyalur', 'Udayarpalayam', 'உடையார்பாளையம்', 'taluk'),
('cpt_chengalpattu', 'chengalpattu', 'Chengalpattu', 'செங்கல்பட்டு', 'taluk'),
('cpt_cheyyur', 'chengalpattu', 'Cheyyur', 'செய்யூர்', 'taluk'),
('cpt_maduranthakam', 'chengalpattu', 'Maduranthakam', 'மதுராந்தகம்', 'taluk'),
('cpt_pallavaram', 'chengalpattu', 'Pallavaram', 'பல்லாவரம்', 'taluk'),
('cpt_tambaram', 'chengalpattu', 'Tambaram', 'தாம்பரம்', 'taluk'),
('cpt_tirukalukundram', 'chengalpattu', 'Tirukalukundram', 'திருக்கழுக்குன்றம்', 'taluk'),
('cpt_tiruporur', 'chengalpattu', 'Tiruporur', 'திருப்போரூர்', 'taluk'),
('cpt_vandalur', 'chengalpattu', 'Vandalur', 'வண்டலூர்', 'taluk'),
('chn_alandur', 'chennai', 'Alandur', 'ஆலந்தூர்', 'taluk'),
('chn_ambattur', 'chennai', 'Ambattur', 'அம்பத்தூர்', 'taluk'),
('chn_aminjikarai', 'chennai', 'Aminjikarai', 'அமிஞ்சிக்கரை', 'taluk'),
('chn_ayanavaram', 'chennai', 'Ayanavaram', 'அயனாவரம்', 'taluk'),
('chn_egmore', 'chennai', 'Egmore', 'எழும்பூர்', 'taluk'),
('chn_guindy', 'chennai', 'Guindy', 'கிண்டி', 'taluk'),
('chn_madhavaram', 'chennai', 'Madhavaram', 'மாதவரம்', 'taluk'),
('chn_maduravoyal', 'chennai', 'Maduravoyal', 'மதுரவாயல்', 'taluk'),
('chn_mambalam', 'chennai', 'Mambalam', 'மாம்பலம்', 'taluk'),
('chn_mylapore', 'chennai', 'Mylapore', 'மயிலாப்பூர்', 'taluk'),
('chn_perambur', 'chennai', 'Perambur', 'பெரம்பூர்', 'taluk'),
('chn_purasawalkam', 'chennai', 'Purasawalkam', 'புரசைவாக்கம்', 'taluk'),
('chn_sholinganallur', 'chennai', 'Sholinganallur', 'சோழிங்கநல்லூர்', 'taluk'),
('chn_thiruvottiyur', 'chennai', 'Thiruvottiyur', 'திருவொற்றியூர்', 'taluk'),
('chn_tondiarpet', 'chennai', 'Tondiarpet', 'தண்டையார்பேட்டை', 'taluk'),
('chn_velachery', 'chennai', 'Velachery', 'வேளச்சேரி', 'taluk'),
('cbe_anaimalai', 'coimbatore', 'Anaimalai', 'ஆனைமலை', 'taluk'),
('cbe_annur', 'coimbatore', 'Annur', 'அன்னூர்', 'taluk'),
('cbe_north', 'coimbatore', 'Coimbatore North', 'கோயம்புத்தூர் வடக்கு', 'taluk'),
('cbe_south', 'coimbatore', 'Coimbatore South', 'கோயம்புத்தூர் தெற்கு', 'taluk'),
('cbe_kinathukadavu', 'coimbatore', 'Kinathukadavu', 'கிணத்துக்கடவு', 'taluk'),
('cbe_madukkarai', 'coimbatore', 'Madukkarai', 'மதுக்கரை', 'taluk'),
('cbe_mettupalayam', 'coimbatore', 'Mettupalayam', 'மேட்டுப்பாளையம்', 'taluk'),
('cbe_perur', 'coimbatore', 'Perur', 'பேரூர்', 'taluk'),
('cbe_pollachi', 'coimbatore', 'Pollachi', 'பொள்ளாச்சி', 'taluk'),
('cbe_sulur', 'coimbatore', 'Sulur', 'சூலூர்', 'taluk'),
('cbe_valparai', 'coimbatore', 'Valparai', 'வால்பாறை', 'taluk'),
('cud_bhuvanagiri', 'cuddalore', 'Bhuvanagiri', 'புவனகிரி', 'taluk'),
('cud_chidambaram', 'cuddalore', 'Chidambaram', 'சிதம்பரம்', 'taluk'),
('cud_cuddalore', 'cuddalore', 'Cuddalore', 'கடலூர்', 'taluk'),
('cud_kattumannarkoil', 'cuddalore', 'Kattumannarkoil', 'காட்டுமன்னார்கோயில்', 'taluk'),
('cud_kurinjipadi', 'cuddalore', 'Kurinjipadi', 'குறிஞ்சிப்பாடி', 'taluk'),
('cud_panruti', 'cuddalore', 'Panruti', 'பண்ருட்டி', 'taluk'),
('cud_srimushnam', 'cuddalore', 'Srimushnam', 'ஸ்ரீமுஷ்ணம்', 'taluk'),
('cud_tittakudi', 'cuddalore', 'Tittakudi', 'திட்டக்குடி', 'taluk'),
('cud_veppur', 'cuddalore', 'Veppur', 'வேப்பூர்', 'taluk'),
('cud_vriddhachalam', 'cuddalore', 'Vriddhachalam', 'விருத்தாசலம்', 'taluk'),
('dpi_dharmapuri', 'dharmapuri', 'Dharmapuri', 'தர்மபுரி', 'taluk'),
('dpi_harur', 'dharmapuri', 'Harur', 'அரூர்', 'taluk'),
('dpi_karimangalam', 'dharmapuri', 'Karimangalam', 'காரிமங்கலம்', 'taluk'),
('dpi_nallampalli', 'dharmapuri', 'Nallampalli', 'நல்லம்பள்ளி', 'taluk'),
('dpi_palacode', 'dharmapuri', 'Palacode', 'பாலக்கோடு', 'taluk'),
('dpi_pappireddipatti', 'dharmapuri', 'Pappireddipatti', 'பாப்பிரெட்டிப்பட்டி', 'taluk'),
('dpi_pennagaram', 'dharmapuri', 'Pennagaram', 'பென்னாகரம்', 'taluk'),
('dgl_attur', 'dindigul', 'Attur', 'ஆத்தூர்', 'taluk'),
('dgl_dindigul_east', 'dindigul', 'Dindigul East', 'திண்டுக்கல் கிழக்கு', 'taluk'),
('dgl_dindigul_west', 'dindigul', 'Dindigul West', 'திண்டுக்கல் மேற்கு', 'taluk'),
('dgl_gujjiliamparai', 'dindigul', 'Gujjiliamparai', 'குஜிலியம்பாறை', 'taluk'),
('dgl_kodaikanal', 'dindigul', 'Kodaikanal', 'கொடைக்கானல்', 'taluk'),
('dgl_natham', 'dindigul', 'Natham', 'நத்தம்', 'taluk'),
('dgl_nilakkottai', 'dindigul', 'Nilakkottai', 'நிலக்கோட்டை', 'taluk'),
('dgl_oddanchatram', 'dindigul', 'Oddanchatram', 'ஒட்டன்சத்திரம்', 'taluk'),
('dgl_palani', 'dindigul', 'Palani', 'பழனி', 'taluk'),
('dgl_vedasandur', 'dindigul', 'Vedasandur', 'வேடசந்தூர்', 'taluk'),
('erd_anthiyur', 'erode', 'Anthiyur', 'அந்தியூர்', 'taluk'),
('erd_bhavani', 'erode', 'Bhavani', 'பவானி', 'taluk'),
('erd_erode', 'erode', 'Erode', 'ஈரோடு', 'taluk'),
('erd_gobichettipalayam', 'erode', 'Gobichettipalayam', 'கோபிசெட்டிபாளையம்', 'taluk'),
('erd_kodumudi', 'erode', 'Kodumudi', 'கொடுமுடி', 'taluk'),
('erd_modakkurichi', 'erode', 'Modakkurichi', 'மொடக்குறிச்சி', 'taluk'),
('erd_nambiyur', 'erode', 'Nambiyur', 'நம்பியூர்', 'taluk'),
('erd_perundurai', 'erode', 'Perundurai', 'பெருந்துறை', 'taluk'),
('erd_sathyamangalam', 'erode', 'Sathyamangalam', 'சத்தியமங்கலம்', 'taluk'),
('erd_thalavadi', 'erode', 'Thalavadi', 'தாளவாடி', 'taluk'),
('kki_chinnasalem', 'kallakurichi', 'Chinnasalem', 'சின்னசேலம்', 'taluk'),
('kki_kallakurichi', 'kallakurichi', 'Kallakurichi', 'கள்ளக்குறிச்சி', 'taluk'),
('kki_kalvarayan_hills', 'kallakurichi', 'Kalvarayan Hills', 'கல்வராயன் மலை', 'taluk'),
('kki_sankarapuram', 'kallakurichi', 'Sankarapuram', 'சங்கராபுரம்', 'taluk'),
('kki_tirukoilur', 'kallakurichi', 'Tirukoilur', 'திருக்கோவிலூர்', 'taluk'),
('kki_ulundurpet', 'kallakurichi', 'Ulundurpet', 'உளுந்தூர்பேட்டை', 'taluk'),
('kki_vanapuram', 'kallakurichi', 'Vanapuram', 'வானாபுரம்', 'taluk'),
('kpm_kancheepuram', 'kancheepuram', 'Kancheepuram', 'காஞ்சிபுரம்', 'taluk'),
('kpm_kundrathur', 'kancheepuram', 'Kundrathur', 'குன்றத்தூர்', 'taluk'),
('kpm_sriperumbudur', 'kancheepuram', 'Sriperumbudur', 'ஸ்ரீபெரும்புதூர்', 'taluk'),
('kpm_uthiramerur', 'kancheepuram', 'Uthiramerur', 'உத்திரமேரூர்', 'taluk'),
('kpm_walajabad', 'kancheepuram', 'Walajabad', 'வாலாஜாபாத்', 'taluk'),
('kkm_agastheeswaram', 'kanniyakumari', 'Agastheeswaram', 'அகத்தீஸ்வரம்', 'taluk'),
('kkm_kalkulam', 'kanniyakumari', 'Kalkulam', 'கல்குளம்', 'taluk'),
('kkm_killiyoor', 'kanniyakumari', 'Killiyoor', 'கிள்ளியூர்', 'taluk'),
('kkm_thiruvattar', 'kanniyakumari', 'Thiruvattar', 'திருவட்டார்', 'taluk'),
('kkm_thovalai', 'kanniyakumari', 'Thovalai', 'தோவாளை', 'taluk'),
('kkm_vilavancode', 'kanniyakumari', 'Vilavancode', 'விளவங்கோடு', 'taluk'),
('krr_aravakurichi', 'karur', 'Aravakurichi', 'அரவக்குறிச்சி', 'taluk'),
('krr_kadavur', 'karur', 'Kadavur', 'கடவூர்', 'taluk'),
('krr_karur', 'karur', 'Karur', 'கரூர்', 'taluk'),
('krr_krishnarayapuram', 'karur', 'Krishnarayapuram', 'கிருஷ்ணராயபுரம்', 'taluk'),
('krr_kulithalai', 'karur', 'Kulithalai', 'குளித்தலை', 'taluk'),
('krr_manmangalam', 'karur', 'Manmangalam', 'மண்மங்கலம்', 'taluk'),
('krr_pugalur', 'karur', 'Pugalur', 'புகழூர்', 'taluk'),
('kgi_bargur', 'krishnagiri', 'Bargur', 'பர்கூர்', 'taluk'),
('kgi_denkanikottai', 'krishnagiri', 'Denkanikottai', 'தேன்கனிக்கோட்டை', 'taluk'),
('kgi_hosur', 'krishnagiri', 'Hosur', 'ஓசூர்', 'taluk'),
('kgi_kelamangalam', 'krishnagiri', 'Kelamangalam', 'கேளமங்கலம்', 'taluk'),
('kgi_krishnagiri', 'krishnagiri', 'Krishnagiri', 'கிருஷ்ணகிரி', 'taluk'),
('kgi_pochampalli', 'krishnagiri', 'Pochampalli', 'போச்சம்பள்ளி', 'taluk'),
('kgi_shoolagiri', 'krishnagiri', 'Shoolagiri', 'சூளகிரி', 'taluk'),
('kgi_uthangarai', 'krishnagiri', 'Uthangarai', 'ஊத்தங்கரை', 'taluk'),
('mdu_kallikudi', 'madurai', 'Kallikudi', 'கள்ளிக்குடி', 'taluk'),
('mdu_madurai_east', 'madurai', 'Madurai East', 'மதுரை கிழக்கு', 'taluk'),
('mdu_north', 'madurai', 'Madurai North', 'மதுரை வடக்கு', 'taluk'),
('mdu_south', 'madurai', 'Madurai South', 'மதுரை தெற்கு', 'taluk'),
('mdu_madurai_west', 'madurai', 'Madurai West', 'மதுரை மேற்கு', 'taluk'),
('mdu_melur', 'madurai', 'Melur', 'மேலூர்', 'taluk'),
('mdu_peraiyur', 'madurai', 'Peraiyur', 'பேரையூர்', 'taluk'),
('mdu_thirumangalam', 'madurai', 'Thirumangalam', 'திருமங்கலம்', 'taluk'),
('mdu_thiruparankundram', 'madurai', 'Thiruparankundram', 'திருப்பரங்குன்றம்', 'taluk'),
('mdu_usilampatti', 'madurai', 'Usilampatti', 'உசிலம்பட்டி', 'taluk'),
('mdu_vadipatti', 'madurai', 'Vadipatti', 'வாடிப்பட்டி', 'taluk'),
('myd_kuthalam', 'mayiladuthurai', 'Kuthalam', 'குத்தாலம்', 'taluk'),
('myd_mayiladuthurai', 'mayiladuthurai', 'Mayiladuthurai', 'மயிலாடுதுறை', 'taluk'),
('myd_sirkazhi', 'mayiladuthurai', 'Sirkazhi', 'சீர்காழி', 'taluk'),
('myd_tharangambadi', 'mayiladuthurai', 'Tharangambadi', 'தரங்கம்பாடி', 'taluk'),
('ngp_kilvelur', 'nagapattinam', 'Kilvelur', 'கீழ்வேளூர்', 'taluk'),
('ngp_nagapattinam', 'nagapattinam', 'Nagapattinam', 'நாகப்பட்டினம்', 'taluk'),
('ngp_thirukkuvalai', 'nagapattinam', 'Thirukkuvalai', 'திருக்குவளை', 'taluk'),
('ngp_vedaranyam', 'nagapattinam', 'Vedaranyam', 'வேதாரண்யம்', 'taluk'),
('nmk_kolli_hills', 'namakkal', 'Kolli Hills', 'கொல்லிமலை', 'taluk'),
('nmk_kumarapalayam', 'namakkal', 'Kumarapalayam', 'குமாரபாளையம்', 'taluk'),
('nmk_mohanur', 'namakkal', 'Mohanur', 'மோகனூர்', 'taluk'),
('nmk_namakkal', 'namakkal', 'Namakkal', 'நாமக்கல்', 'taluk'),
('nmk_paramathi_velur', 'namakkal', 'Paramathi Velur', 'பரமத்தி வேலூர்', 'taluk'),
('nmk_rasipuram', 'namakkal', 'Rasipuram', 'ராசிபுரம்', 'taluk'),
('nmk_sendamangalam', 'namakkal', 'Sendamangalam', 'சேந்தமங்கலம்', 'taluk'),
('nmk_tiruchengode', 'namakkal', 'Tiruchengode', 'திருச்செங்கோடு', 'taluk'),
('nil_coonoor', 'nilgiris', 'Coonoor', 'குன்னூர்', 'taluk'),
('nil_gudalur', 'nilgiris', 'Gudalur', 'கூடலூர்', 'taluk'),
('nil_kotagiri', 'nilgiris', 'Kotagiri', 'கோத்தகிரி', 'taluk'),
('nil_kundah', 'nilgiris', 'Kundah', 'குந்தா', 'taluk'),
('nil_pandalur', 'nilgiris', 'Pandalur', 'பந்தலூர்', 'taluk'),
('nil_udhagamandalam', 'nilgiris', 'Udhagamandalam', 'உதகமண்டலம்', 'taluk'),
('pbl_alathur', 'perambalur', 'Alathur', 'ஆலத்தூர்', 'taluk'),
('pbl_kunnam', 'perambalur', 'Kunnam', 'குன்னம்', 'taluk'),
('pbl_perambalur', 'perambalur', 'Perambalur', 'பெரம்பலூர்', 'taluk'),
('pbl_veppanthattai', 'perambalur', 'Veppanthattai', 'வேப்பந்தட்டை', 'taluk'),
('pdk_alangudi', 'pudukkottai', 'Alangudi', 'ஆலங்குடி', 'taluk'),
('pdk_aranthangi', 'pudukkottai', 'Aranthangi', 'அறந்தாங்கி', 'taluk'),
('pdk_avudaiyarkoil', 'pudukkottai', 'Avudaiyarkoil', 'ஆவுடையார்கோவில்', 'taluk'),
('pdk_gandarvakottai', 'pudukkottai', 'Gandarvakottai', 'கந்தர்வக்கோட்டை', 'taluk'),
('pdk_illuppur', 'pudukkottai', 'Illuppur', 'இலுப்பூர்', 'taluk'),
('pdk_karambakkudi', 'pudukkottai', 'Karambakkudi', 'கறம்பக்குடி', 'taluk'),
('pdk_kulathur', 'pudukkottai', 'Kulathur', 'குளத்தூர்', 'taluk'),
('pdk_manamelkudi', 'pudukkottai', 'Manamelkudi', 'மணமேல்குடி', 'taluk'),
('pdk_ponnamaravathi', 'pudukkottai', 'Ponnamaravathi', 'பொன்னமராவதி', 'taluk'),
('pdk_pudukkottai', 'pudukkottai', 'Pudukkottai', 'புதுக்கோட்டை', 'taluk'),
('pdk_thirumayam', 'pudukkottai', 'Thirumayam', 'திருமயம்', 'taluk'),
('pdk_viralimalai', 'pudukkottai', 'Viralimalai', 'விராலிமலை', 'taluk'),
('ram_kadaladi', 'ramanathapuram', 'Kadaladi', 'கடலாடி', 'taluk'),
('ram_kamuthi', 'ramanathapuram', 'Kamuthi', 'கமுதி', 'taluk'),
('ram_kilakarai', 'ramanathapuram', 'Kilakarai', 'கீழக்கரை', 'taluk'),
('ram_mudukulathur', 'ramanathapuram', 'Mudukulathur', 'முதுகுளத்தூர்', 'taluk'),
('ram_paramakudi', 'ramanathapuram', 'Paramakudi', 'பரமக்குடி', 'taluk'),
('ram_ramanathapuram', 'ramanathapuram', 'Ramanathapuram', 'இராமநாதபுரம்', 'taluk'),
('ram_rameswaram', 'ramanathapuram', 'Rameswaram', 'ராமேஸ்வரம்', 'taluk'),
('ram_r_s_mangalam', 'ramanathapuram', 'RS Mangalam', 'ஆர்.எஸ்.மங்கலம்', 'taluk'),
('ram_tiruvadanai', 'ramanathapuram', 'Tiruvadanai', 'திருவாடானை', 'taluk'),
('rpt_arakkonam', 'ranipet', 'Arakkonam', 'அரக்கோணம்', 'taluk'),
('rpt_arcot', 'ranipet', 'Arcot', 'ஆற்காடு', 'taluk'),
('rpt_nemili', 'ranipet', 'Nemili', 'நெமிலி', 'taluk'),
('rpt_ranipet', 'ranipet', 'Ranipet', 'ராணிப்பேட்டை', 'taluk'),
('rpt_sholinghur', 'ranipet', 'Sholinghur', 'சோளிங்கர்', 'taluk'),
('rpt_walajah', 'ranipet', 'Walajah', 'வாலாஜா', 'taluk'),
('slm_attur', 'salem', 'Attur', 'ஆத்தூர்', 'taluk'),
('slm_edappadi', 'salem', 'Edappadi', 'எடப்பாடி', 'taluk'),
('slm_gangavalli', 'salem', 'Gangavalli', 'கங்கவல்லி', 'taluk'),
('slm_kadaiyampatti', 'salem', 'Kadaiyampatti', 'காடையாம்பட்டி', 'taluk'),
('slm_mettur', 'salem', 'Mettur', 'மேட்டூர்', 'taluk'),
('slm_omalur', 'salem', 'Omalur', 'ஓமலூர்', 'taluk'),
('slm_salem', 'salem', 'Salem', 'சேலம்', 'taluk'),
('slm_salem_south', 'salem', 'Salem South', 'சேலம் தெற்கு', 'taluk'),
('slm_salem_west', 'salem', 'Salem West', 'சேலம் மேற்கு', 'taluk'),
('slm_sankari', 'salem', 'Sankari', 'சங்ககிரி', 'taluk'),
('slm_thalaivasal', 'salem', 'Thalaivasal', 'தலைவாசல்', 'taluk'),
('slm_valapady', 'salem', 'Valapady', 'வாழப்பாடி', 'taluk'),
('slm_yercaud', 'salem', 'Yercaud', 'ஏற்காடு', 'taluk'),
('svg_devakottai', 'sivaganga', 'Devakottai', 'தேவகோட்டை', 'taluk'),
('svg_ilayangudi', 'sivaganga', 'Ilayangudi', 'இளையான்குடி', 'taluk'),
('svg_kalaiyarkovil', 'sivaganga', 'Kalaiyarkovil', 'காளையார்கோவில்', 'taluk'),
('svg_karaikudi', 'sivaganga', 'Karaikudi', 'காரைக்குடி', 'taluk'),
('svg_manamadurai', 'sivaganga', 'Manamadurai', 'மானாமதுரை', 'taluk'),
('svg_singampunari', 'sivaganga', 'Singampunari', 'சிங்கம்புணரி', 'taluk'),
('svg_sivaganga', 'sivaganga', 'Sivaganga', 'சிவகங்கை', 'taluk'),
('svg_thiruppuvanam', 'sivaganga', 'Thiruppuvanam', 'திருப்புவனம்', 'taluk'),
('svg_tiruppattur', 'sivaganga', 'Tiruppattur', 'திருப்பத்தூர்', 'taluk'),
('tks_alankulam', 'tenkasi', 'Alankulam', 'ஆலங்குளம்', 'taluk'),
('tks_kadayanallur', 'tenkasi', 'Kadayanallur', 'கடையநல்லூர்', 'taluk'),
('tks_sankarankovil', 'tenkasi', 'Sankarankovil', 'சங்கரன்கோவில்', 'taluk'),
('tks_shenkottai', 'tenkasi', 'Shenkottai', 'செங்கோட்டை', 'taluk'),
('tks_sivagiri', 'tenkasi', 'Sivagiri', 'சிவகிரி', 'taluk'),
('tks_tenkasi', 'tenkasi', 'Tenkasi', 'தென்காசி', 'taluk'),
('tks_thiruvengadam', 'tenkasi', 'Thiruvengadam', 'திருவேங்கடம்', 'taluk'),
('tks_veerakeralamputhur', 'tenkasi', 'Veerakeralamputhur', 'வீரகேரளம்புதூர்', 'taluk'),
('tjr_budalur', 'thanjavur', 'Budalur', 'பூதலூர்', 'taluk'),
('tjr_kumbakonam', 'thanjavur', 'Kumbakonam', 'கும்பகோணம்', 'taluk'),
('tjr_orathanadu', 'thanjavur', 'Orathanadu', 'ஒரத்தநாடு', 'taluk'),
('tjr_papanasam', 'thanjavur', 'Papanasam', 'பாபநாசம்', 'taluk'),
('tjr_pattukkottai', 'thanjavur', 'Pattukkottai', 'பட்டுக்கோட்டை', 'taluk'),
('tjr_peravurani', 'thanjavur', 'Peravurani', 'பேராவூரணி', 'taluk'),
('tjr_thanjavur', 'thanjavur', 'Thanjavur', 'தஞ்சாவூர்', 'taluk'),
('tjr_thiruvaiyaru', 'thanjavur', 'Thiruvaiyaru', 'திருவையாறு', 'taluk'),
('tjr_thiruvidaimarudur', 'thanjavur', 'Thiruvidaimarudur', 'திருவிடைமருதூர்', 'taluk'),
('tni_andipatti', 'theni', 'Andipatti', 'ஆண்டிபட்டி', 'taluk'),
('tni_bodinayakanur', 'theni', 'Bodinayakanur', 'போடிநாயக்கனூர்', 'taluk'),
('tni_periyakulam', 'theni', 'Periyakulam', 'பெரியகுளம்', 'taluk'),
('tni_theni', 'theni', 'Theni', 'தேனி', 'taluk'),
('tni_uthamapalayam', 'theni', 'Uthamapalayam', 'உத்தமபாளையம்', 'taluk'),
('tcy_alwarthirunagari', 'thoothukudi', 'Alwarthirunagari', 'ஆழ்வார்திருநகரி', 'taluk'),
('tcy_eral', 'thoothukudi', 'Eral', 'ஏரல்', 'taluk'),
('tcy_kayathar', 'thoothukudi', 'Kayathar', 'கயத்தாறு', 'taluk'),
('tcy_kovilpatti', 'thoothukudi', 'Kovilpatti', 'கோவில்பட்டி', 'taluk'),
('tcy_ottapidaram', 'thoothukudi', 'Ottapidaram', 'ஒட்டப்பிடாரம்', 'taluk'),
('tcy_sattankulam', 'thoothukudi', 'Sattankulam', 'சாத்தான்குளம்', 'taluk'),
('tcy_srivaikuntam', 'thoothukudi', 'Srivaikuntam', 'ஸ்ரீவைகுண்டம்', 'taluk'),
('tcy_thoothukudi', 'thoothukudi', 'Thoothukudi', 'தூத்துக்குடி', 'taluk'),
('tcy_tiruchendur', 'thoothukudi', 'Tiruchendur', 'திருச்செந்தூர்', 'taluk'),
('tcy_vilathikulam', 'thoothukudi', 'Vilathikulam', 'விளாத்திகுளம்', 'taluk'),
('try_lalgudi', 'tiruchirappalli', 'Lalgudi', 'லால்குடி', 'taluk'),
('try_manachanallur', 'tiruchirappalli', 'Manachanallur', 'மண்ணச்சநல்லூர்', 'taluk'),
('try_manapparai', 'tiruchirappalli', 'Manapparai', 'மணப்பாறை', 'taluk'),
('try_marungapuri', 'tiruchirappalli', 'Marungapuri', 'மருங்காபுரி', 'taluk'),
('try_musiri', 'tiruchirappalli', 'Musiri', 'முசிறி', 'taluk'),
('try_srirangam', 'tiruchirappalli', 'Srirangam', 'ஸ்ரீரங்கம்', 'taluk'),
('try_thiruverumbur', 'tiruchirappalli', 'Thiruverumbur', 'திருவெறும்பூர்', 'taluk'),
('try_thottiyam', 'tiruchirappalli', 'Thottiyam', 'தொட்டியம்', 'taluk'),
('try_thuraiyur', 'tiruchirappalli', 'Thuraiyur', 'துறையூர்', 'taluk'),
('try_trichy_east', 'tiruchirappalli', 'Tiruchirappalli East', 'திருச்சிராப்பள்ளி கிழக்கு', 'taluk'),
('try_trichy_west', 'tiruchirappalli', 'Tiruchirappalli West', 'திருச்சிராப்பள்ளி மேற்கு', 'taluk'),
('tnv_ambasamudram', 'tirunelveli', 'Ambasamudram', 'அம்பாசமுத்திரம்', 'taluk'),
('tnv_cheranmahadevi', 'tirunelveli', 'Cheranmahadevi', 'சேரன்மகாதேவி', 'taluk'),
('tnv_manur', 'tirunelveli', 'Manur', 'மானூர்', 'taluk'),
('tnv_nanguneri', 'tirunelveli', 'Nanguneri', 'நாங்குநேரி', 'taluk'),
('tnv_palayamkottai', 'tirunelveli', 'Palayamkottai', 'பாளையங்கோட்டை', 'taluk'),
('tnv_radhapuram', 'tirunelveli', 'Radhapuram', 'ராதாபுரம்', 'taluk'),
('tnv_tirunelveli', 'tirunelveli', 'Tirunelveli', 'திருநெல்வேலி', 'taluk'),
('tnv_tisayanvilai', 'tirunelveli', 'Tisayanvilai', 'திசையன்விளை', 'taluk'),
('tpt_ambur', 'tirupathur', 'Ambur', 'ஆம்பூர்', 'taluk'),
('tpt_natrampalli', 'tirupathur', 'Natrampalli', 'நாட்ராம்பள்ளி', 'taluk'),
('tpt_tirupathur', 'tirupathur', 'Tirupathur', 'திருப்பத்தூர்', 'taluk'),
('tpt_vaniyambadi', 'tirupathur', 'Vaniyambadi', 'வாணியம்பாடி', 'taluk'),
('tup_avinashi', 'tiruppur', 'Avinashi', 'அவினாசி', 'taluk'),
('tup_dharapuram', 'tiruppur', 'Dharapuram', 'தாராபுரம்', 'taluk'),
('tup_kangeyam', 'tiruppur', 'Kangeyam', 'காங்கேயம்', 'taluk'),
('tup_madathukulam', 'tiruppur', 'Madathukulam', 'மடத்துக்குளம்', 'taluk'),
('tup_palladam', 'tiruppur', 'Palladam', 'பல்லடம்', 'taluk'),
('tup_tiruppur_north', 'tiruppur', 'Tiruppur North', 'திருப்பூர் வடக்கு', 'taluk'),
('tup_tiruppur_south', 'tiruppur', 'Tiruppur South', 'திருப்பூர் தெற்கு', 'taluk'),
('tup_udumalaipettai', 'tiruppur', 'Udumalaipettai', 'உடுமலைப்பேட்டை', 'taluk'),
('tup_uthukuli', 'tiruppur', 'Uthukuli', 'ஊத்துக்குளி', 'taluk'),
('tlr_avadi', 'tiruvallur', 'Avadi', 'ஆவடி', 'taluk'),
('tlr_gummidipoondi', 'tiruvallur', 'Gummidipoondi', 'கும்மிடிப்பூண்டி', 'taluk'),
('tlr_pallipattu', 'tiruvallur', 'Pallipattu', 'பள்ளிப்பட்டு', 'taluk'),
('tlr_ponneri', 'tiruvallur', 'Ponneri', 'பொன்னேரி', 'taluk'),
('tlr_poonamallee', 'tiruvallur', 'Poonamallee', 'பூந்தமல்லி', 'taluk'),
('tlr_rk_pet', 'tiruvallur', 'RK Pet', 'ஆர்.கே.பேட்டை', 'taluk'),
('tlr_tiruttani', 'tiruvallur', 'Tiruttani', 'திருத்தணி', 'taluk'),
('tlr_tiruvallur', 'tiruvallur', 'Tiruvallur', 'திருவள்ளூர்', 'taluk'),
('tlr_uthukottai', 'tiruvallur', 'Uthukottai', 'ஊத்துக்கோட்டை', 'taluk'),
('tvm_arani', 'tiruvannamalai', 'Arani', 'ஆரணி', 'taluk'),
('tvm_chengam', 'tiruvannamalai', 'Chengam', 'செங்கம்', 'taluk'),
('tvm_chetpet', 'tiruvannamalai', 'Chetpet', 'சேத்துப்பட்டு', 'taluk'),
('tvm_cheyyar', 'tiruvannamalai', 'Cheyyar', 'செய்யாறு', 'taluk'),
('tvm_jawadhu_hills', 'tiruvannamalai', 'Jawadhu Hills', 'ஜவ்வாது மலை', 'taluk'),
('tvm_kalasapakkam', 'tiruvannamalai', 'Kalasapakkam', 'கலசப்பாக்கம்', 'taluk'),
('tvm_kilpennathur', 'tiruvannamalai', 'Kilpennathur', 'கீழ்பென்னாத்தூர்', 'taluk'),
('tvm_polur', 'tiruvannamalai', 'Polur', 'போளூர்', 'taluk'),
('tvm_thandarampattu', 'tiruvannamalai', 'Thandarampattu', 'தண்டராம்பட்டு', 'taluk'),
('tvm_tiruvannamalai', 'tiruvannamalai', 'Tiruvannamalai', 'திருவண்ணாமலை', 'taluk'),
('tvm_vandavasi', 'tiruvannamalai', 'Vandavasi', 'வந்தவாசி', 'taluk'),
('tvm_vembakkam', 'tiruvannamalai', 'Vembakkam', 'வெம்பாக்கம்', 'taluk'),
('tvr_koothanallur', 'tiruvarur', 'Koothanallur', 'கூத்தநல்லூர்', 'taluk'),
('tvr_kudavasal', 'tiruvarur', 'Kudavasal', 'குடவாசல்', 'taluk'),
('tvr_mannargudi', 'tiruvarur', 'Mannargudi', 'மன்னார்குடி', 'taluk'),
('tvr_nannilam', 'tiruvarur', 'Nannilam', 'நன்னிலம்', 'taluk'),
('tvr_needamangalam', 'tiruvarur', 'Needamangalam', 'நீடாமங்கலம்', 'taluk'),
('tvr_thiruthuraipoondi', 'tiruvarur', 'Thiruthuraipoondi', 'திருத்துறைப்பூண்டி', 'taluk'),
('tvr_tiruvarur', 'tiruvarur', 'Tiruvarur', 'திருவாரூர்', 'taluk'),
('tvr_valangaiman', 'tiruvarur', 'Valangaiman', 'வலங்கைமான்', 'taluk'),
('vel_anaicut', 'vellore', 'Anaicut', 'அணைக்கட்டு', 'taluk'),
('vel_gudiyatham', 'vellore', 'Gudiyatham', 'குடியாத்தம்', 'taluk'),
('vel_katpadi', 'vellore', 'Katpadi', 'காட்பாடி', 'taluk'),
('vel_kv_kuppam', 'vellore', 'KV Kuppam', 'கே.வி.குப்பம்', 'taluk'),
('vel_pernambut', 'vellore', 'Pernambut', 'பேரணாம்பட்டு', 'taluk'),
('vel_vellore', 'vellore', 'Vellore', 'வேலூர்', 'taluk'),
('vpm_gingee', 'viluppuram', 'Gingee', 'செஞ்சி', 'taluk'),
('vpm_kandachipuram', 'viluppuram', 'Kandachipuram', 'கண்டாச்சிபுரம்', 'taluk'),
('vpm_marakkanam', 'viluppuram', 'Marakkanam', 'மரக்காணம்', 'taluk'),
('vpm_melmalayanur', 'viluppuram', 'Melmalayanur', 'மேல்மலையனூர்', 'taluk'),
('vpm_thiruvennainallur', 'viluppuram', 'Thiruvennainallur', 'திருவெண்ணைநல்லூர்', 'taluk'),
('vpm_tindivanam', 'viluppuram', 'Tindivanam', 'திண்டிவனம்', 'taluk'),
('vpm_vanur', 'viluppuram', 'Vanur', 'வானூர்', 'taluk'),
('vpm_vikravandi', 'viluppuram', 'Vikravandi', 'விக்ரவாண்டி', 'taluk'),
('vpm_viluppuram', 'viluppuram', 'Viluppuram', 'விழுப்புரம்', 'taluk'),
('vnr_aruppukkottai', 'virudhunagar', 'Aruppukkottai', 'அருப்புக்கோட்டை', 'taluk'),
('vnr_kariyapatti', 'virudhunagar', 'Kariyapatti', 'காரியாபட்டி', 'taluk'),
('vnr_rajapalayam', 'virudhunagar', 'Rajapalayam', 'ராஜபாளையம்', 'taluk'),
('vnr_sattur', 'virudhunagar', 'Sattur', 'சாத்தூர்', 'taluk'),
('vnr_sivakasi', 'virudhunagar', 'Sivakasi', 'சிவகாசி', 'taluk'),
('vnr_srivilliputhur', 'virudhunagar', 'Srivilliputhur', 'ஸ்ரீவில்லிபுத்தூர்', 'taluk'),
('vnr_tiruchuli', 'virudhunagar', 'Tiruchuli', 'திருச்சுழி', 'taluk'),
('vnr_vembakottai', 'virudhunagar', 'Vembakottai', 'வெம்பக்கோட்டை', 'taluk'),
('vnr_virudhunagar', 'virudhunagar', 'Virudhunagar', 'விருதுநகர்', 'taluk'),
('vnr_watrap', 'virudhunagar', 'Watrap', 'வத்திராயிருப்பு', 'taluk')
ON CONFLICT (id) DO UPDATE SET
  district_id = EXCLUDED.district_id,
  name = EXCLUDED.name,
  tamil_name = EXCLUDED.tamil_name,
  type = EXCLUDED.type;
