version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: crowdcity:latest
    container_name: crowdcity_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/usr/src/app/logs
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - LOG_TO_FILE=true
